"""Ed25519-signed merchant authorisation.

A mandate is the merchant saying, cryptographically: "this agent may take
these action types, up to these amounts, until this instant." The agent cannot
widen its own mandate, because it does not hold the signing key -- only the
merchant does. The agent holds the public key and can therefore verify, but
not forge.

The demo keypair lives in data/mandates/ and is generated by
`python -m chitragupta.mandate --generate`. It is a test key with no value;
the point is that the verification path is real, not that the key is secret.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from pydantic import BaseModel, Field

from .canonical import canonical_json
from .types import ActionType


class Mandate(BaseModel):
    """The merchant's signed grant of authority to the agent."""

    model_config = {"frozen": True}

    mandate_id: str
    merchant_id: str
    permitted_actions: list[ActionType]
    #: Hard ceiling. An action above this is DENIED outright.
    max_amount_paise: int = Field(ge=0)
    #: Above this but below the ceiling, the action is permitted in kind but
    #: needs the merchant to confirm -- STEP_UP rather than ALLOW.
    auto_execute_limit_paise: int = Field(ge=0)
    #: Cap on remediation attempts per payment (stopping rule 1).
    max_attempts_per_payment: int = Field(ge=1, default=3)
    not_before: str  # ISO 8601 UTC
    not_after: str  # ISO 8601 UTC
    public_key_hex: str

    def signing_payload(self) -> bytes:
        """Exactly the bytes that get signed -- the mandate minus its signature."""
        return canonical_json(self)


class SignedMandate(BaseModel):
    model_config = {"frozen": True}

    mandate: Mandate
    signature_hex: str

    def verify(self) -> bool:
        """True iff the signature matches the mandate's own embedded public key."""
        try:
            pub = Ed25519PublicKey.from_public_bytes(
                bytes.fromhex(self.mandate.public_key_hex)
            )
            pub.verify(bytes.fromhex(self.signature_hex), self.mandate.signing_payload())
            return True
        except (InvalidSignature, ValueError):
            return False


def sign_mandate(mandate: Mandate, private_key: Ed25519PrivateKey) -> SignedMandate:
    sig = private_key.sign(mandate.signing_payload())
    return SignedMandate(mandate=mandate, signature_hex=sig.hex())


def parse_iso(ts: str) -> datetime:
    """Parse an ISO 8601 timestamp, treating a naive one as UTC."""
    dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def generate_keypair() -> tuple[Ed25519PrivateKey, str]:
    priv = Ed25519PrivateKey.generate()
    pub_hex = priv.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    ).hex()
    return priv, pub_hex


def _main() -> int:
    ap = argparse.ArgumentParser(description="Generate the demo mandate keypair.")
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--merchant", default="quickmart")
    ap.add_argument("--out", default="data/mandates")
    # Limits are the MERCHANT's choice, so they are arguments rather than
    # constants. They are scaled to each demo merchant's ticket distribution:
    # an auto-execute limit below the typical ticket would step up almost
    # every retry, which tests nothing.
    ap.add_argument("--auto-limit-paise", type=int, default=1_500_00)
    ap.add_argument("--ceiling-paise", type=int, default=25_000_00)
    args = ap.parse_args()
    if not args.generate:
        ap.print_help()
        return 1

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    priv, pub_hex = generate_keypair()

    mandate = Mandate(
        mandate_id="mandate_%s_v1" % args.merchant,
        merchant_id=args.merchant,
        permitted_actions=[
            ActionType.RESCHEDULE_BILLING_WINDOW,
            ActionType.RETRY_SOFT_DECLINE,
            ActionType.REISSUE_PAYMENT_LINK,
            ActionType.ENABLE_MULTI_BANK_ROUTING,
            ActionType.UPDATE_PAYMENT_METHOD,
            ActionType.RENEW_MANDATE,
            ActionType.FLAG_FOR_INVESTIGATION,
        ],
        max_amount_paise=args.ceiling_paise,
        auto_execute_limit_paise=args.auto_limit_paise,
        max_attempts_per_payment=3,
        not_before="2026-01-01T00:00:00Z",
        not_after="2026-12-31T23:59:59Z",
        public_key_hex=pub_hex,
    )
    signed = sign_mandate(mandate, priv)
    assert signed.verify(), "freshly signed mandate failed to verify"

    (out / ("%s_mandate.json" % args.merchant)).write_text(
        json.dumps(signed.model_dump(mode="json"), indent=2),
        encoding="utf-8",
        newline="\n",
    )
    (out / ("%s_signing_key.hex" % args.merchant)).write_text(
        priv.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption(),
        ).hex(),
        encoding="utf-8",
    )
    print("wrote %s/%s_mandate.json (verified)" % (out, args.merchant))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
