"""Hand-labelled ground truth for Razorpay's payment error taxonomy.

Run:  python scripts/build_error_labels.py   ->  evals/error_labels.json

Every code in Razorpay's published xlsx is labelled here by hand, once. The
labels are the ground truth the classification eval in §4.1 scores against,
so they are checked into the repo as data rather than regenerated by a model.

Why an LLM is used at all, given this file exists: the deterministic cache in
classify.py answers every code that appears here without an API call. The
LLM's real job is the code it has NEVER seen -- gateways emit codes outside
the published taxonomy and new ones appear over time. That is why the eval
holds out CODES rather than rows, and why the headline number is generalisation
to unseen codes rather than lookup accuracy.

Label definitions
-----------------
soft_decline  temporary, customer-side or limit-related; the same payment
              could succeed later without anything being changed
hard_decline  permanent for this instrument or configuration; retrying the
              identical request cannot work
technical     infrastructure failed at bank, gateway, PSP or network
auth_failure  the customer failed or abandoned authentication

`recoverable` is deliberately NOT a restatement of the class. It asks whether
an agent acting alone can plausibly convert this payment. Auth failures are
recoverable by the CUSTOMER but not by the agent, so they are False.
"""

from __future__ import annotations

import json
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "data" / "razorpay" / "payment_error_reasons.xlsx"
OUT = ROOT / "evals" / "error_labels.json"

S, H, T, A = "soft_decline", "hard_decline", "technical", "auth_failure"

# code -> (class, recoverable)
LABELS: dict[str, tuple[str, bool]] = {
    "amount_less_than_minimum_amount": (H, False),
    "authentication_failed": (A, False),
    "authorisation_declined_by_psp": (T, True),
    "bank_account_invalid": (H, False),
    "bank_account_validation_failed": (H, False),
    "bank_cutoff_in_progress": (T, True),
    "bank_not_available": (T, True),
    "bank_not_enabled": (H, False),
    "bank_technical_error": (T, True),
    "beneficiary_account_does_not_exist": (H, False),
    "beneficiary_account_dormant": (H, False),
    "capture_failed": (T, True),
    "card_declined": (S, True),
    "card_expired": (H, False),
    "card_network_not_enabled": (H, False),
    "card_not_enrolled": (H, False),
    "card_number_invalid": (H, False),
    "card_type_invalid": (H, False),
    "collect_on_mcc_blocked": (H, False),
    "collect_request_pending": (S, True),
    "compliance_violation": (H, False),
    "credit_limit_exceeded": (S, True),
    "credit_limit_expired": (H, False),
    "credit_limit_inactive": (H, False),
    "credit_limit_not_approved": (H, False),
    "credit_not_permitted": (T, True),
    "credit_failed": (T, True),
    "debit_declined": (S, True),
    "deemed_transaction": (T, True),
    "debit_instrument_blocked": (H, False),
    "debit_instrument_inactive": (H, False),
    "duplicate_refund_id": (H, False),
    "duplicate_request": (H, False),
    "duplicate_rrn_found": (T, True),
    "emi_greater_than_max_amount": (H, False),
    "emi_plan_unavailable": (H, False),
    "funds_blocked_by_mandate": (S, True),
    "gateway_technical_error": (T, True),
    "incorrect_atm_pin": (A, False),
    "incorrect_card_details": (A, False),
    "incorrect_card_expiry_date": (A, False),
    "incorrect_cardholder_name": (A, False),
    "incorrect_cvv": (A, False),
    "incorrect_otp": (A, False),
    "incorrect_pin": (A, False),
    "input_validation_failed": (H, False),
    "insufficient_funds": (S, True),
    "international_transaction_not_allowed": (H, False),
    "invalid_amount": (H, False),
    "invalid_currency": (H, False),
    "invalid_device": (A, False),
    "invalid_email": (H, False),
    "invalid_mobile_number": (H, False),
    "invalid_order_id": (H, False),
    "invalid_response_from_gateway": (T, True),
    "invalid_request": (H, False),
    "invalid_user_details": (H, False),
    "invalid_vpa": (H, False),
    "issuer_technical_error": (T, True),
    "live_mode_not_enabled": (H, False),
    "mandate_creation_declined": (H, False),
    "mandate_creation_expired": (H, False),
    "mandate_creation_failed": (H, False),
    "mandate_creation_timeout": (T, True),
    "mcc_amount_limit_exceeded": (H, False),
    "merchant_not_activated": (H, False),
    "mismatch_in_transaction_details": (H, False),
    "mobile_number_invalid": (H, False),
    "order_already_paid": (H, False),
    "order_payment_method_mismatch": (H, False),
    "order_amount_mismatch": (H, False),
    "otp_attempts_exceeded": (A, False),
    "otp_expired": (A, False),
    "payment_amount_tampered": (H, False),
    "payment_cancelled": (A, False),
    "payment_collect_request_expired": (S, True),
    "payment_declined": (S, True),
    "payment_declined_due_to_high_traffic": (T, True),
    "payment_failed": (T, True),
    "payment_method_not_enabled": (H, False),
    "payment_pending": (S, True),
    "payment_pending_approval": (S, True),
    "payment_risk_check_failed": (H, False),
    "payment_session_expired": (S, True),
    "payment_timed_out": (T, True),
    "pin_attempts_exceeded": (A, False),
    "pin_not_set": (A, False),
    # NOTE the stray space: this is how Razorpay actually publishes it.
    "psp_app_ not_available": (T, True),
    "psp_app_not_supported": (H, False),
    "psp_not_available": (T, True),
    "psp_not_registered": (H, False),
    "record_not_found": (T, True),
    "recurring_payment_not_enabled": (H, False),
    "refund_limit_crossed": (H, False),
    "reqauth_mandate_not_acknowledged": (T, True),
    "request_timed_out": (T, True),
    "server_error": (T, True),
    "transaction_daily_count_exceeded": (S, True),
    "transaction_daily_limit_exceeded": (S, True),
    "transaction_limit_exceeded": (S, True),
    "transaction_frequency_limit_exceeded": (S, True),
    "transaction_on_vpa_restricted": (H, False),
    "upi_app_technical_error": (T, True),
    "upi_autopay_not_supported_on_psp": (H, False),
    "upi_collect_not_enabled": (H, False),
    "upi_intent_not_enabled": (H, False),
    "user_not_eligible": (H, False),
    "user_not_registered_for_netbanking": (H, False),
    "vpa_resolution_failed": (T, True),
    "verification_failed": (T, True),
}


def load_taxonomy() -> dict[str, dict[str, str]]:
    ws = openpyxl.load_workbook(XLSX, read_only=True).worksheets[0]
    rows = [r for r in ws.iter_rows(values_only=True) if r and r[0] and str(r[0]).strip()]
    out: dict[str, dict[str, str]] = {}
    for r in rows[1:]:
        code = str(r[0]).strip()
        out.setdefault(
            code,
            {
                "explanation": str(r[1] or "").strip(),
                "next_steps": str(r[2] or "").strip(),
            },
        )
    return out


def main() -> int:
    taxonomy = load_taxonomy()
    missing = sorted(set(taxonomy) - set(LABELS))
    extra = sorted(set(LABELS) - set(taxonomy))
    if missing:
        raise SystemExit(
            "%d code(s) in the xlsx are unlabelled -- label them before the "
            "eval can run:\n  %s" % (len(missing), "\n  ".join(missing))
        )
    if extra:
        print("WARN  %d labelled code(s) no longer in the xlsx: %s" % (len(extra), extra))

    records = []
    for code, meta in sorted(taxonomy.items()):
        cls, recoverable = LABELS[code]
        records.append(
            {
                "code": code,
                "explanation": meta["explanation"],
                "next_steps": meta["next_steps"],
                "category": cls,
                "recoverable": recoverable,
            }
        )

    counts: dict[str, int] = {}
    for r in records:
        counts[r["category"]] = counts.get(r["category"], 0) + 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "source": "data/razorpay/payment_error_reasons.xlsx",
                "n_codes": len(records),
                "class_support": counts,
                "labels": records,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    print("wrote %s" % OUT.relative_to(ROOT))
    print("  %d codes" % len(records))
    for k in sorted(counts, key=lambda k: -counts[k]):
        print("  %-14s %3d  (%4.1f%%)" % (k, counts[k], 100 * counts[k] / len(records)))
    n_rec = sum(1 for r in records if r["recoverable"])
    print("  recoverable    %3d  (%4.1f%%)" % (n_rec, 100 * n_rec / len(records)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
